<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
<script src="<%=basePath%>assert/theme/js/jquery-1.10.2.min.js"></script>
<script src="<%=basePath%>assert/theme/js/jquery-migrate-1.2.1.min.js"></script>
<script src="<%=basePath%>assert/theme/js/jquery-ui.js"></script>
<!--loading bootstrap js-->
<script src="<%=basePath%>assert/theme/vendors/bootstrap/js/bootstrap.min.js"></script>
<script src="<%=basePath%>assert/theme/vendors/bootstrap-hover-dropdown/bootstrap-hover-dropdown.js"></script>
<script src="<%=basePath%>assert/theme/js/html5shiv.js"></script>
<script src="<%=basePath%>assert/theme/js/respond.min.js"></script>
<script src="<%=basePath%>assert/theme/vendors/metisMenu/jquery.metisMenu.js"></script>
<script src="<%=basePath%>assert/theme/vendors/slimScroll/jquery.slimscroll.js"></script>
<script src="<%=basePath%>assert/theme/vendors/jquery-cookie/jquery.cookie.js"></script>
<script src="<%=basePath%>assert/theme/vendors/iCheck/icheck.min.js"></script>
<script src="<%=basePath%>assert/theme/vendors/iCheck/custom.min.js"></script>
<script src="<%=basePath%>assert/theme/vendors/jquery-notific8/jquery.notific8.min.js"></script>
<script src="<%=basePath%>assert/theme/vendors/jquery-highcharts/highcharts.js"></script>
<script src="<%=basePath%>assert/theme/js/jquery.menu.js"></script>
<script src="<%=basePath%>assert/theme/vendors/jquery-pace/pace.min.js"></script>
<script src="<%=basePath%>assert/theme/vendors/holder/holder.js"></script>
<script src="<%=basePath%>assert/theme/vendors/responsive-tabs/responsive-tabs.js"></script>
<script src="<%=basePath%>assert/theme/vendors/jquery-news-ticker/jquery.newsTicker.min.js"></script>
<script src="<%=basePath%>assert/theme/vendors/moment/moment.js"></script>
<script src="<%=basePath%>assert/theme/vendors/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script src="<%=basePath%>assert/theme/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
<!--CORE JAVASCRIPT-->
<script src="<%=basePath%>assert/theme/js/main.js"></script>
<!--LOADING SCRIPTS FOR PAGE-->
<script src="<%=basePath%>assert/theme/vendors/intro.js/intro.js"></script>
<script src="<%=basePath%>assert/theme/vendors/flot-chart/jquery.flot.js"></script>
<script src="<%=basePath%>assert/theme/vendors/flot-chart/jquery.flot.categories.js"></script>
<script src="<%=basePath%>assert/theme/vendors/flot-chart/jquery.flot.pie.js"></script>
<script src="<%=basePath%>assert/theme/vendors/flot-chart/jquery.flot.tooltip.js"></script>
<script src="<%=basePath%>assert/theme/vendors/flot-chart/jquery.flot.resize.js"></script>
<script src="<%=basePath%>assert/theme/vendors/flot-chart/jquery.flot.fillbetween.js"></script>
<script src="<%=basePath%>assert/theme/vendors/flot-chart/jquery.flot.stack.js"></script>
<script src="<%=basePath%>assert/theme/vendors/flot-chart/jquery.flot.spline.js"></script>
<script src="<%=basePath%>assert/theme/vendors/calendar/zabuto_calendar.min.js"></script>
<script src="<%=basePath%>assert/theme/vendors/sco.message/sco.message.js"></script>
<script src="<%=basePath%>assert/theme/vendors/intro.js/intro.js"></script>
<script src="<%=basePath%>assert/theme/js/index.js"></script>
